### ISSUE TITLE
Set the adapter title to the widget's name

### ISSUE THREAD

**Issue by nialscorva** [ozone-development/ozp-iwc-owf7-widget-adapter#13]
The adapter's title is always set to "OWF7 Adapter".  Set the title to the following:

1. The "name" from the system API for that widget.
2. The widget's host and path, followed by " -- OWF Widget"  (e.g. "example.com/widget/myWidget.html -- OWF Widget"

**Comment by Kevin-K** [comment]
>1. The "name" from the system API for that widget.

The name is only obtainable if the `GUID` of the widget is known. Widget param's are passed to the iframe initialization through the hash of the adapter, should the course of action be to gather the GUID from the hash else fall back to option 2? 

A bulk get of the system.api `/application` resource list could match a URL -> launchUrl -> GUID. but has the side-effect of potentially longer load time if the user has a large amounts of applications. Also I believe launchUrl's arent managed as strictly unique so there can be issues of multiple application listings able to claim as a match.

**Comment by Kevin-K** [comment]
**Is the title needed at time of widget instantiation?** 
The title is not included in the iframe's window.name config in owf7, thus gathering the data from system.api asynchronously while the iframe is loaded seems to be a viable option.
```
generateIframeName:function (url, objectId, widget, paneType, launchData, isLocked) {
                var iframeNameObj = {
                    id:objectId,

                    containerVersion:Ozone.version.owfversion,
                    webContextPath:Ozone.config.webContextPath,
                    preferenceLocation:Ozone.config.prefsLocation,

                    relayUrl:this.getContainerRelay(),
                    lang:Ozone.lang.getLanguage(),
                    currentTheme:Ozone.config.currentTheme,
                    owf:true,
                    layout:paneType || "",
                    url:url,
                    guid:widget.widgetGuid,
                    version:widget.version || 1,
                    locked: isLocked || false
                };

                if (launchData) {
                    iframeNameObj.data = launchData;
                }

                //return this json object as formatted string which is appropriate for being put in the name attribute of the
                //iframe tag.
                return iframeNameObj;

            }
```

**Comment by Kevin-K** [comment]
handled in #16
